/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;


/**
 *
 * @author Jenny May
 */
public class Order extends javax.swing.JFrame {
String class_order;
String dis;
int total;
    /**
     * Creates new form Order
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Yumburger = new javax.swing.JButton();
        Spaghetti = new javax.swing.JButton();
        Burger = new javax.swing.JButton();
        Breakfast = new javax.swing.JButton();
        Soups = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Chickenjoy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 51, 51)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 535));

        Yumburger.setBackground(new java.awt.Color(255, 255, 255));
        Yumburger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Yumburger.setText("Yumburger");
        Yumburger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Yumburger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YumburgerActionPerformed(evt);
            }
        });

        Spaghetti.setBackground(new java.awt.Color(255, 255, 255));
        Spaghetti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Spaghetti.setText("Jolly Spaghetti");
        Spaghetti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Spaghetti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpaghettiActionPerformed(evt);
            }
        });

        Burger.setBackground(new java.awt.Color(255, 255, 255));
        Burger.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Burger.setText("Burger Steak");
        Burger.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurgerActionPerformed(evt);
            }
        });

        Breakfast.setBackground(new java.awt.Color(255, 255, 255));
        Breakfast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Breakfast.setText("Breakfast");
        Breakfast.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Breakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreakfastActionPerformed(evt);
            }
        });

        Soups.setBackground(new java.awt.Color(255, 255, 255));
        Soups.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Soups.setText("Soups and Sides");
        Soups.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Soups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoupsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        Chickenjoy.setBackground(new java.awt.Color(255, 255, 255));
        Chickenjoy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Chickenjoy.setText("Chickenjoy");
        Chickenjoy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Chickenjoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChickenjoyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Chickenjoy, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Yumburger, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Spaghetti, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Burger, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Breakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Soups, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Yumburger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Soups, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Breakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Burger, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Spaghetti, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Chickenjoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 535);

        setSize(new java.awt.Dimension(817, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChickenjoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChickenjoyActionPerformed
        this.dispose();
        receipt bre = new receipt();
       
        receipt.menu1.setText("Chickenjoy Solo");
        receipt.menu2.setText("Chickenjoy w/ Spaghetti");
        receipt.menu3.setText("Chickenjoy w/ Burger Steak");
        receipt.menu4.setText("Chickenjoy w/ Fries");
        receipt.menu5.setText("Chickenjoy w/ Palabok");
        receipt.menu6.setText("Chickenjoy Set of Peach Mango");
        receipt.menu7.setText("6 pc Chickenjoy Solo");
        bre.setVisible(true);
        
        
    }//GEN-LAST:event_ChickenjoyActionPerformed

    private void SpaghettiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpaghettiActionPerformed
        this.dispose();
        receipt Spag = new receipt();
       
        receipt.menu1.setText("Spaghetti Solo");
        receipt.menu2.setText("Spaghetti w/ Cheezy YumBurger");
        receipt.menu3.setText("Spaghetti w/ YumBurger");
        receipt.menu4.setText("Spaghetti w/ Fries ");
        receipt.menu5.setText("Spaghetti Family fan");
        receipt.menu6.hide();
        receipt.menu7.hide();
        Spag.setVisible(true);
    }//GEN-LAST:event_SpaghettiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new jframe().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void YumburgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YumburgerActionPerformed
        this.dispose();
        receipt yum = new receipt();
       
        receipt.menu1.setText("Yumburger Solo");
        receipt.menu2.setText("Cheesy Deluxe Yumburger");
        receipt.menu3.setText("Bacon Cheesy Yumburger");
        receipt.menu4.setText("Champ with fries");
        receipt.menu5.setText("Double Bacon Yum w/ Fries");
        receipt.menu6.setText("Bacon Cheesy Yum with Fries");
        receipt.menu7.setText("Yumburger w/ Fries ");
        yum.setVisible(true);
    }//GEN-LAST:event_YumburgerActionPerformed

    private void BurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurgerActionPerformed
        this.dispose();
        receipt bur = new receipt();
       
        receipt.menu1.setText("Burger Steak Solo");
        receipt.menu2.setText("Burger Steak Supreme w/ Fries");
        receipt.menu3.setText("Big Burger Steak Supreme");
        receipt.menu4.setText("Burger Steak w/ Shanghai");
        receipt.menu5.hide(); receipt.num_palabok.hide();
        receipt.menu6.hide(); receipt.num_mango.hide();
        receipt.menu7.hide(); receipt.num_set.hide();
        bur.setVisible(true);
    }//GEN-LAST:event_BurgerActionPerformed

    private void BreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreakfastActionPerformed
        this.dispose();
        receipt bre = new receipt();
       
        receipt.menu1.setText("Chickenjoy with Coffee");
        receipt.menu2.setText("Burger Steak with Coffee");
        receipt.menu3.setText("Corned Beef w/ coffee");
        receipt.menu4.setText("Beef tapa w/ coffee");
        receipt.menu5.setText("Lonnganisa w/ coffee");
        receipt.menu6.setText("Shanghai w/ Coffee");
        receipt.menu7.setText("2 Pancake w/ Coffee");
        bre.setVisible(true);
    }//GEN-LAST:event_BreakfastActionPerformed

    private void SoupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoupsActionPerformed
        this.dispose();
        receipt soups = new receipt();
       
        receipt.menu1.setText("Jolly Crispy Fries-Jumbo");
        receipt.menu2.setText("Jolly Crispy Fries-Large");
        receipt.menu3.setText("Jolly Crispy Fries-Regular");
        receipt.menu4.setText("Butterd Corn");
        receipt.menu5.setText("Creamy Macaroni Soup");
        receipt.menu6.hide(); receipt.num_mango.hide();
        receipt.menu7.hide(); receipt.num_set.hide();
        soups.setVisible(true);
    }//GEN-LAST:event_SoupsActionPerformed

    
    public static void main(String args[]) {
        
        /* Set the Nimbus look feel */
        //<editor-fold defaultstate="collapsed" desc=" Look feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Breakfast;
    private javax.swing.JButton Burger;
    private javax.swing.JButton Chickenjoy;
    private javax.swing.JButton Soups;
    private javax.swing.JButton Spaghetti;
    public static javax.swing.JButton Yumburger;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
